### PR TITLE
mediacodec: Import system_properties from CAF.

### PR DESCRIPTION
**Pull request by Thaodan**
Imported from vendor-qcom-opensource-media as of 182649923d3813e2e539a0e36d83b3e70dcfcc4a:
https://github.com/sonyxperiadev/vendor-qcom-opensource-media/tree/182649923d3813e2e539a0e36d83b3e70dcfcc4a

Required for: https://github.com/sonyxperiadev/local_manifests/pull/127

### CODE REVIEW

**Comment by MarijnS95** [comment]
Would this automagically ship itself to the device? Missing a `PRODUCT_COPY_FILES` or `prebuilt_file` here :grimacing:

**Comment by Thaodan** [comment]
Should be better now.

**Comment by MarijnS95** [comment]
Does this fix anything for https://github.com/sonyxperiadev/local_manifests/pull/127 or is that still up for testing? I was eyeing different - xml - files...

The seccomp policy is already contained and shared in common, and I've not seen this `system_properties.xml` before, looks like `PRODUCT_PROPERTIES`? Is it the media HAL that reads this specifically or AOSP that "amends" it to the build.prop "environment"?

**Comment by MarijnS95** [comment]
The files I'm referring to are `edo/rootdir/vendor/etc/media_codecs*.xml`.

**Comment by jerpelea** [comment]
@MarijnS95 
system_properties.xml is read by libplatformconfig

**Comment by Thaodan** [comment]
> Does this fix anything for
> https://github.com/sonyxperiadev/local_manifests/pull/127 or is that still
> up for testing? I was eyeing different - xml - files...
> 
Yes with system_properties.xml present in /vendor/etc the PR works, its also 
present in stock.

**Comment by MarijnS95** [comment]
Drop `seccomp policy` from the title, then we're all good for merge. Thanks for testing and digging, I'll update the other PR.

**Comment by MarijnS95** [comment]
There are other platforms with random vidc issues, perhaps we should revisit those too?

**Comment by Thaodan** [comment]
Done, I will update seccomp policy too in common:
https://github.com/sonyxperiadev/device-sony-common/pull/881

**Pull request merged**
